extends:
  - airbnb
  - prettier
  - plugin:prettier/recommended
plugins:
  - prettier
env:
  es6: true
  browser: true
globals:
  expect: true
  it: true
  describe: true
  Attach: true
parser: '@babel/eslint-parser'
rules:
  strict: 0
  import/no-extraneous-dependencies: 0
  prettier/prettier: error
ignorePatterns:
  - '**/*.min.js'
